import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {OrbitControls} from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';
const $=id=>document.getElementById(id), clamp=(x,a,b)=>Math.max(a,Math.min(b,x)), rad=THREE.MathUtils.degToRad;
const S={lat:-89.5,lon:0,t:0,sites:[]};
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(45,1,.1,100);
camera.position.set(7,4.5,9);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('canvas').appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=4.2;controls.maxDistance=17;
scene.add(new THREE.AmbientLight(0x68758a,.22));
const light=new THREE.DirectionalLight(0xffffff,3.5);scene.add(light);
function tex(kind){const c=document.createElement('canvas');c.width=c.height=512,x=c.getContext('2d');
if(kind==='moon'){let g=x.createRadialGradient(250,230,20,250,250,290);g.addColorStop(0,'#d2d0ca');g.addColorStop(1,'#55575b');x.fillStyle=g;x.fillRect(0,0,512,512);for(let i=0;i<180;i++){x.fillStyle='rgba(25,27,29,'+(Math.random()*.3)+')';x.beginPath();x.arc(Math.random()*512,Math.random()*512,2+Math.random()*13,0,7);x.fill()}}
else{let g=x.createLinearGradient(0,0,512,512);g.addColorStop(0,'#153e72');g.addColorStop(.6,'#2675a8');g.addColorStop(1,'#071a30');x.fillStyle=g;x.fillRect(0,0,512,512);for(let i=0;i<25;i++){x.fillStyle='rgba(80,160,95,.4)';x.beginPath();x.ellipse(Math.random()*512,Math.random()*512,20+Math.random()*70,8+Math.random()*30,Math.random()*6,0,7);x.fill()}}let t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
const moon=new THREE.Mesh(new THREE.SphereGeometry(2,96,64),new THREE.MeshStandardMaterial({map:tex('moon'),roughness:1}));scene.add(moon);
const earth=new THREE.Mesh(new THREE.SphereGeometry(.58,48,32),new THREE.MeshStandardMaterial({map:tex('earth'),roughness:.9}));scene.add(earth);
const atmo=new THREE.Mesh(new THREE.SphereGeometry(.65,32,24),new THREE.MeshBasicMaterial({color:0x55aaff,transparent:true,opacity:.12,side:THREE.BackSide}));scene.add(atmo);
const sun=new THREE.Mesh(new THREE.SphereGeometry(.7,32,24),new THREE.MeshBasicMaterial({color:0xffd66b}));scene.add(sun);
const stars=new THREE.BufferGeometry(),pts=[];for(let i=0;i<1200;i++){let u=Math.random()*2-1,a=Math.random()*7,s=Math.sqrt(1-u*u);pts.push(55*s*Math.cos(a),55*u,55*s*Math.sin(a))}stars.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));scene.add(new THREE.Points(stars,new THREE.PointsMaterial({color:0xb9c9e6,size:.04})));
const marker=new THREE.Mesh(new THREE.SphereGeometry(.055,16,12),new THREE.MeshBasicMaterial({color:0x6ee7a8}));scene.add(marker);
function vec(lat,lon,r=2.02){let p=rad(90-lat),q=rad(lon);return new THREE.Vector3(r*Math.sin(p)*Math.cos(q),r*Math.cos(p),r*Math.sin(p)*Math.sin(q))}
function sd(){let a=S.t/29.53059*Math.PI*2;return new THREE.Vector3(Math.cos(a),.18*Math.sin(2*a),Math.sin(a)).normalize()}
function phase(){let p=S.t/29.53059;if(p<.0625||p>.9375)return'NEW MOON';if(p<.3125)return'WAXING QUARTER';if(p<.5625)return'FULL MOON';return'WANING QUARTER'}
function update3d(){let s=sd(),e=s.clone().multiplyScalar(-1);sun.position.copy(s).multiplyScalar(8);light.position.copy(sun.position);light.target.position.set(0,0,0);scene.add(light.target);earth.position.copy(e).multiplyScalar(6.2);atmo.position.copy(earth.position);const p=vec(S.lat,S.lon),n=p.clone().normalize();marker.position.copy(p);let elev=Math.asin(clamp(n.dot(s),-1,1))*180/Math.PI,ep=Math.asin(clamp(n.dot(e),-1,1))*180/Math.PI,ip=clamp((elev+10)/100,0,1);$('elev').textContent=elev.toFixed(1)+'°';$('illum').textContent=Math.round(ip*100)+'%';$('earth').textContent=ep>0?Math.round(ep)+'° above':'Below horizon';$('temp').textContent=elev>0?Math.round(80+elev*.55)+' K':'~80 K';$('light').textContent=elev>0?'SUNLIGHT':'NIGHT';$('phase').textContent=phase();$('phaseSmall').textContent='LUNAR PHASE · DAY '+S.t.toFixed(2)}
function terrain(){let a=Math.abs(S.lat);return{slope:clamp(2.5+Math.abs(Math.sin(rad(S.lat*3+S.lon)))*8,1,14),rough:clamp(12+Math.abs(Math.sin(rad(S.lat*4-S.lon)))*50,5,65),risk:clamp(10+Math.abs(Math.cos(rad(S.lat*2+S.lon*.8)))*55,5,80),comm:clamp(45+Math.cos(rad(S.lat))*30+Math.cos(rad(S.lon))*20,15,98)}}
function data(name=S.name||$('name').value||'Candidate'){let t=terrain(),n=vec(S.lat,S.lon).normalize(),e=Math.asin(clamp(n.dot(sd()),-1,1))*180/Math.PI,illum=clamp((e+10)/100,0,1),score=clamp(100-t.slope*2.3-t.rough*.25-t.risk*.22+t.comm*.12+illum*22,18,97),analogue=Math.abs(S.lat)>70?'Antarctic Dry Valleys':t.rough>45?'Hawaiian volcanic terrain':Math.abs(S.lat)<25?'Atacama Desert':'Icelandic lava fields';
let pros=[];if(t.slope<6)pros.push('Relatively gentle landing slope');if(e>15)pros.push('Strong solar elevation at this mission time');if(t.risk<35)pros.push('Lower estimated crater / rock hazard');if(t.comm>65)pros.push('Favorable Earth-visibility geometry');if(!pros.length)pros.push('Useful candidate for comparison');
let risks=[];if(t.slope>=6)risks.push('Steeper terrain increases landing difficulty');if(e<=15)risks.push('Low-angle or absent sunlight at this time');if(t.risk>=35)risks.push('Higher estimated crater / rock exposure');if(t.rough>=40)risks.push('More variable surface roughness');if(!risks.length)risks.push('No dominant modeled risk at this time');
return{name,lat:S.lat,lon:S.lon,...t,e,illum,score,analogue,pros,risks}}
function render(){let d=data();$('siteTitle').textContent=d.name;$('class').textContent=d.score>=80?'PREFERRED':d.score>=65?'PROMISING':'HIGHER RISK';$('slope').textContent=d.slope.toFixed(1)+'°';$('rough').textContent=Math.round(d.rough)+'/100';$('risk').textContent=Math.round(d.risk)+'/100';$('comm').textContent=Math.round(d.comm)+'/100';$('analogue').textContent=d.analogue;$('reason').textContent='A practical Earth environment for field-testing and analog research, not a physical match to lunar conditions.';$('pros').innerHTML=d.pros.map(x=>'<li>'+x+'</li>').join('');$('risks').innerHTML=d.risks.map(x=>'<li>'+x+'</li>').join('');$('mini').innerHTML='<b style="font-size:25px;color:#9fc1ff">'+Math.round(d.score)+'</b><br><small>LANDING SUITABILITY SCREEN</small>';$('summary').textContent=`${d.name} scores ${Math.round(d.score)}/100 in this prototype. Strongest factors: ${d.pros.slice(0,2).join(' and ').toLowerCase()}. Main watch items: ${d.risks.slice(0,2).join(' and ').toLowerCase()}. Earth analogue: ${d.analogue}.`;update3d()}
function renderList(){let box=$('list');if(!S.sites.length){box.innerHTML='<div class="empty">Add two or more candidates to compare their pros, risks and scores.</div>';$('winner').innerHTML='';return}box.innerHTML=S.sites.map((d,i)=>`<div class="candidate"><div><b>${d.name}</b><small>${d.lat.toFixed(2)}°, ${d.lon.toFixed(2)}° · slope ${d.slope.toFixed(1)}° · hazard ${Math.round(d.risk)}/100</small></div><div class="score">${Math.round(d.score)}</div><button data-v="${i}">VIEW</button><button data-r="${i}">REMOVE</button></div>`).join('');box.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{let d=S.sites[+b.dataset.v];$('name').value=d.name;S.lat=d.lat;S.lon=d.lon;$('lat').value=d.lat;$('lon').value=d.lon;render()});box.querySelectorAll('[data-r]').forEach(b=>{b.onclick=()=>{S.sites.splice(+b.dataset.r,1);renderList()}});if(S.sites.length>1){let best=[...S.sites].sort((a,b)=>b.score-a.score)[0];$('winner').innerHTML='<b>BEST OF THESE CANDIDATES:</b> '+best.name+' — '+Math.round(best.score)+'/100. '+best.pros[0]+'.'}}
$('analyze').onclick=()=>{S.lat=clamp(+$('lat').value,-90,90);S.lon=clamp(+$('lon').value,-180,180);render()};
$('add').onclick=()=>{S.sites.push(data($('name').value||'Candidate '+(S.sites.length+1)));renderList()};
$('clear').onclick=()=>{S.sites=[];renderList()};
$('time').oninput=e=>{S.t=+e.target.value;$('day').textContent='Day '+S.t.toFixed(2);let h=Math.floor((S.t%1)*24),m=Math.floor((((S.t%1)*24)%1)*60);$('clock').textContent=String(h).padStart(2,'0')+':'+String(m).padStart(2,'0');render()};
renderer.domElement.addEventListener('pointerdown',e=>{let r=renderer.domElement.getBoundingClientRect(),m=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(m,camera);let h=ray.intersectObject(moon)[0];if(h){let n=h.point.normalize();S.lat=90-THREE.MathUtils.radToDeg(Math.acos(clamp(n.y,-1,1)));S.lon=THREE.MathUtils.radToDeg(Math.atan2(n.z,n.x));$('lat').value=S.lat.toFixed(2);$('lon').value=S.lon.toFixed(2);render()}});
function resize(){let r=$('canvas').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();function loop(){requestAnimationFrame(loop);moon.rotation.y+=.00035;controls.update();renderer.render(scene,camera)}loop();render();